project_name: bedrocktool

before:
  hooks:
    - go mod tidy
    - |
       bash -c "if [ \"$(head -c 7 resourcepack-ace.go)\" != \"package\" ]; then mv nop.notgo resourcepack-ace.go; fi"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - arm64
      - amd64
      - 386
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github: