name: ci-build
on:
  push

jobs:
  run:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

# version number
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ !env.ACT }}

# build
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true
      
      - name: decrypt
        run: |
          sudo apt update -y
          sudo apt install git-crypt xxd -y
          echo ${REPO_KEY} | xxd -r -p > ../bedrock-repo-key.key
          git-crypt unlock ../bedrock-repo-key.key
          rm ../bedrock-repo-key.key
        env:
          REPO_KEY: ${{ secrets.REPO_KEY }}
        if: ${{ !env.ACT }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

