name: ci-build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git fetch --force --tags

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
          cache: true

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: git-crypt xxd
          version: 1.0

      - name: decrypt
        if: ${{ !env.ACT }}
        run: |
          echo ${REPO_KEY} | xxd -r -p > ../bedrock-repo-key.key
          git-crypt unlock ../bedrock-repo-key.key
          rm ../bedrock-repo-key.key
        env:
          REPO_KEY: ${{ secrets.REPO_KEY }}

      - run: go get ./cmd/bedrocktool

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: build
        id: build
        run: |
          python build.py

      - name: Deploy with rsync
        run: rsync -avz ./updates/ olebeck@${{ secrets.SSH_HOST }}:/var/www/updates/bedrocktool/

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.previoustag.outputs.tag }}
          files: ./builds/*
          prerelease: false
