name: ci-build
on:
  push

jobs:
  run:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

# version number
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: minor

# build
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: build
        run: make windows linux mac

# create release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.bump-semver.outputs.new_version }}
          prerelease: true
          title: "Development Build"
          files: |
            bedrocktool_${{ steps.get-latest-tag.outputs.tag }}.exe
            bedrocktool_${{ steps.get-latest-tag.outputs.tag }}-linux
            bedrocktool_${{ steps.get-latest-tag.outputs.tag }}-mac
