name: ci-build
on:
  push

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: decrypt
        if: ${{ !env.ACT }}
        run: |
          sudo apt update -y
          sudo apt install git-crypt xxd -y
          echo ${REPO_KEY} | xxd -r -p > ../bedrock-repo-key.key
          git-crypt unlock ../bedrock-repo-key.key
          rm ../bedrock-repo-key.key
        env:
          REPO_KEY: ${{ secrets.REPO_KEY }}
      
      - run: go get

      - name: build
        run: make -j

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.get-latest-tag.outputs.tag }}
          prerelease: true
          title: "Latest Release"
          files: |
            dist/*

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          title: "Latest Development"
          files: |
            dist/*  
