name: ci-build
on:
  push

jobs:
  run:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: Retrieve version
        run: |
          echo "::set-output name=TAG_NAME::$(git describe --tags)"
        id: version

      - name: build
        run: make
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            bedrocktool_${{ steps.version.outputs.TAG_NAME }}.exe
            bedrocktool_${{ steps.version.outputs.TAG_NAME }}-linux
            bedrocktool_${{ steps.version.outputs.TAG_NAME }}-mac
